services:
 db:
   image: postgres:17
   environment:
     POSTGRES_DB: ${NAME}
     POSTGRES_USER: ${PG_USER}
     POSTGRES_PASSWORD: ${PG_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
 
 django-web:
   build: .
   container_name: django-docker
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     DJANGO_SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${ALLOWED_HOSTS}
     DATABASE_ENGINE: ${ENGINE}
     DATABASE_NAME: ${NAME}
     DATABASE_USERNAME: ${PG_USER}
     DATABASE_PASSWORD: ${PG_PASSWORD}
     DATABASE_HOST: ${HOST}
     DATABASE_PORT: ${PORT}
   env_file:
     - .env
volumes:
   postgres_data: